//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColegioVRHT.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public Persona()
        {
            this.MateriaAlumno = new HashSet<MateriaAlumno>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdTipoDocumento { get; set; }
        public Nullable<int> IdSede { get; set; }
        public int IdTipoPersona { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Sexo { get; set; }
        public string Documento { get; set; }
        public string Direccion { get; set; }
        public Nullable<bool> FlagEstado { get; set; }
    
        public virtual ICollection<MateriaAlumno> MateriaAlumno { get; set; }
        public virtual Sede Sede { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
        public virtual TipoPersona TipoPersona { get; set; }
    }
}
