//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColegioVRHT.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDocumento
    {
        public TipoDocumento()
        {
            this.Alumno = new HashSet<Alumno>();
            this.Docente = new HashSet<Docente>();
            this.Persona = new HashSet<Persona>();
        }
    
        public int IdTipoDocumento { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionCorta { get; set; }
        public bool FlagEstado { get; set; }
    
        public virtual ICollection<Alumno> Alumno { get; set; }
        public virtual ICollection<Docente> Docente { get; set; }
        public virtual ICollection<Persona> Persona { get; set; }
    }
}
