//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColegioVRHT.Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoPersona
    {
        public TipoPersona()
        {
            this.Persona = new HashSet<Persona>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionCorta { get; set; }
        public Nullable<bool> FlagEstado { get; set; }
    
        public virtual ICollection<Persona> Persona { get; set; }
    }
}
